---
- hosts: "{{ hosts }}"
  remote_user:  "{{ user }}"
  become: True
  tasks:
    -  name: Set sources
       copy:
          src: ../config/includes.chroot/etc/apt/sources.list
          dest: /etc/apt/sources.list
          owner: root
          group: root
          mode: 0644
    -  name: Get ROS apt-key
       apt_key: 
          keyserver: hkp://ha.pool.sks-keyservers.net:80
          id: 421C365BD9FF1F717815A3895523BAEEB01FA116
          state: present
    -  name: Update cache
       apt: 
          update_cache: yes
    -  name: Install admin packages
       apt: 
           name: "{{ item }}"
           state: present
       with_lines: 
           - cat ../config/package-lists/administration.list.binary
    -  name: Install logging packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat ../config/package-lists/logging.list.binary
    -  name: Install Presentation packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat ../config/package-lists/presentation.list.binary
    -  name: Install Recoup packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat ../config/package-lists/recoup.list.binary
    -  name: Install Recoup 1 packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat ../config/package-lists/recoup1.list.binary
    -  name: Add ROS kinetic enviroment to global profile
       file:
           src: /opt/ros/kinetic/setup.sh
           dest: /etc/profile.d/ros_kinetic.sh
           owner: root
           group: root
           state: link
    -  name: Install x11vnc service
       copy:
           src: ../config/includes.chroot/etc/systemd/system/x11vnc.service
           dest: /etc/systemd/system/
           owner: root
           group: root
           mode: 0755
    -  name: Start and Enable x11vnc service
       service: 
           name: x11vnc
           state: started
           enabled: yes
